### ISSUE TITLE
App not running after cloning

### ISSUE THREAD

**Issue by Vidhu007** [1hanzla100/developer-portfolio#14]
After running ```git clone```
an error comes after ```npm i```
<img width="671" alt="Screenshot 2022-02-05 at 9 00 37 PM" src="https://user-images.githubusercontent.com/70010512/152648070-ca521987-e016-4d8d-b535-852439319ca9.png">

**Comment by 1hanzla100** [comment]
@Vidhu007 Use Yarn

**Comment by Vidhu007** [comment]
It's working now! I used```npm install --save --legacy-peer-deps```
