### ISSUE TITLE
How to find the list of logos available ?

### ISSUE THREAD

**Issue by JeromevDEV** [1hanzla100/developer-portfolio#18]
Hi,
in `portfolio.js` you display a set of skills using `fontAwesomeClassname: "logos:web3js"` . Where can we find the availables logos ? 

Thank you

**Comment by 1hanzla100** [comment]
@JeromevDEV You can Find all icons on [https://icon-sets.iconify.design/](https://icon-sets.iconify.design/). Search Desired icon and copy and paste its name
