### ISSUE TITLE
I send my clone project url than I see your github profile image in everywhere.

### ISSUE THREAD

**Issue by faizkhan7896** [1hanzla100/developer-portfolio#20]

**Comment by faizkhan7896** [comment]
LIKE THIS

![Screenshot 2022-07-19 at 11 40 38 AM](https://user-images.githubusercontent.com/75300551/179678118-89950401-6256-4ded-8e1d-b51957cfbe4e.png)

**Comment by 1hanzla100** [comment]
@faizkhan7896 Edit `Line 25` and add URL of desired image in `pages/index.js`
