### ISSUE TITLE
[improvement] - Implementation of Prettier & Typescript

### ISSUE THREAD

**Issue by vatsalsinghkv** [1hanzla100/developer-portfolio#42]
So I was contributing to this project and I came to notice that my vscode prettier's setting changed whole file structure, which created a lot of unwanted changes.

I think it'd be better if there's Prettier setup for this project so everyone contributing to it and using it have same formatting.

I'd love to install prettier as dev dependency and use your prettier config for this project with npm script to formatting all the required files

**Comment by 1hanzla100** [comment]
@vatsalsinghkv Yea sure, Feel free to create PR.

**Comment by vatsalsinghkv** [comment]
would it be okay, to run prettier as it'll format a lot of files like .json .css .jsx etc?

**Comment by vatsalsinghkv** [comment]
Hey @1hanzla100,  I have got one question since you are using `props-type` in each components, why didn't you consider using typescript for the project?

**Comment by 1hanzla100** [comment]
> Hey @1hanzla100,  I have got one question since you are using `props-type` in each components, why didn't you consider using typescript for the project?

Sure We can consider this option.

**Comment by vatsalsinghkv** [comment]
> Sure We can consider this option.

Exactly. I think it'd make more sense, as with typescript, we can use types even outside the components, like in `portfolio.js`. We can define `type` or `modal` for projects & experience, so people would have ease in using this template.

**Comment by 1hanzla100** [comment]
Yes exactly

**Comment by vatsalsinghkv** [comment]
Should we try migrating it to typescript? I'd love to work on it

**Comment by 1hanzla100** [comment]
> Should we try migrating it to typescript? I'd love to work on it

Sure. You can.

**Comment by abdulbari149** [comment]
Hi, I just checked your repository. I would also like to help you guys migrate to typescript

**Comment by 1hanzla100** [comment]
@abdulbari149 Yes you can collaborate with @vatsalsinghkv in typescript migration
