### ISSUE TITLE
It would be nice if it could have a blog and certifications section.

### ISSUE THREAD

**Issue by Prakash4844** [1hanzla100/developer-portfolio#47]

**Comment by 1hanzla100** [comment]
@Prakash4844 Feel free to contribute by opening a pull request to add the requested blog and certifications section.

**Comment by Prakash4844** [comment]
Actually i don't know TS and react so, i can't do it. Well, it was just a suggestion. maybe someone would in future.

**Comment by Namishk** [comment]
@1hanzla100  I'd like work on this issue. need to discuss where to put these sections.

**Comment by Prakash4844** [comment]
> @1hanzla100 I'd like work on this issue. need to discuss where to put these sections.

From The Front page i see that Social links are redundant, maybe they can be replaced with Blog, certification etc. Sections 
![image](https://github.com/1hanzla100/developer-portfolio/assets/81550376/ba62b293-5e04-4641-b161-9e3921bf73dc)


See this example from my portfolio 

![image](https://github.com/1hanzla100/developer-portfolio/assets/81550376/77b46b29-dc7f-4518-a0c8-9620eef76e86)

Just a suggestion.

**Comment by 1hanzla100** [comment]
@Namishk We can discuss about these new sections.

**Comment by Namishk** [comment]
I am thinking to add certification section below education and for blogs add a link to blogsite and some sample blogs below projects. @1hanzla100

**Comment by 1hanzla100** [comment]
@Namishk Yes you can add these sections. Feel free to open a PR

**Comment by Vyshnav001** [comment]
@1hanzla100 Can i add Tailwind css?

**Comment by 1hanzla100** [comment]
@Vyshnav001 No you cannot. because core UI is based on bootstrap
