### ISSUE TITLE
Shaking cards (UI)

### ISSUE THREAD

**Issue by RinatValiullov** [1hanzla100/developer-portfolio#7]
When you hover over cards with information about education, they quickly twitch.

https://user-images.githubusercontent.com/9755333/147465673-3d07188c-a6ce-4228-b471-fa66a53157fc.mp4

**Comment by 1hanzla100** [comment]
@RinatValiullov You can reduce its speed in CSS

**Comment by RinatValiullov** [comment]
@1hanzla100  Ok, will try.
