### ISSUE TITLE
Social Section

### ISSUE THREAD

**Issue by himanshuvashisht878** [1hanzla100/developer-portfolio#8]
Add an option to remove icons in the social section. Like I don't want to use Facebook but there is no option to remove the Facebook icon.

**Comment by 1hanzla100** [comment]
@himanshuvashisht878  You Can add and remove icon according to your choice in `components/SocialLinks.jsx`

**Comment by himanshuvashisht878** [comment]
@1hanzla100 Got it thanks bro
